config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  
  root "posts#index"

  resources :users, only: [:edit, :update, :show]

  resources :posts, only: [:new, :create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]


  def new
    @post = Post.new
  end

  def create
    
    @post = Post.new(post_params)

    if @post.save
      redirect_to posts_path
    else
      flash.now[:error]= "Unable to save post"
      render :new, status: :unprocessable_entity
    end

  end

  def index
    @posts = Post.all
  end

  private

  def post_params
    params.require(:post).permit(:title, :body).merge({user_id: current_user.id})
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to posts_path, notice: "Updated user account!"
    else
      flash.now[:error] = "Unable to save your user account"
      render :edit, :unprocessable_entity
    end
  end

  def show

    @user = User.find(current_user.id)

  end

  private

  def user_params

    params.require(:user).permit(:first_name)

  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to user_path(@user) unless @user == current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </head>

  <body>
    <h1>Members only!</h1>
    <% if user_signed_in? %>
        <%= link_to "Profile", user_path(current_user.id) %>
        <%= button_to "Sign Out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path %>
        <%= link_to "Sign Up", new_user_registration_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h2>All the posts in this bitch</h2>
<%= link_to "Create New Post", new_post_path %>

<ul>
    <% @posts.each do |post| %>
    <li>
        <h1><%= post.title %></h1>
        <p><%= post.body %> </p>
        <% if user_signed_in? %>
            <p>Posted by: <%= User.find(post.user_id).first_name || "Anonymous" %> </p>
        <% end %>
    </li>
    <% end %>
</ul>

app/views/posts/new.html.erb
<% flash.each do |name, message| %>
    <div>
        <%= content_tag :div, message, class:name %>
    </div>
<% end %>
<%= form_with model: @post do |form| %>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :body %>
        <%= form.text_area :body %>
    </div>
    <%= form.submit "Create Post" %>
<% end %>

app/views/users/edit.html.erb
<% flash.each do |name, message| %>
    <div>
        <%= content_tag :div, message, class:name %>
    </div>
<% end %>
<%= form_with model: @user do |form| %>
    <div>
        <%= form.label :first_name %>
        <%= form.text_field :first_name, value: current_user.first_name %>
    </div>
    <%= form.submit "Update" %>
<% end %>

<%= link_to "Back", user_path(current_user.id) %>

app/views/users/show.html.erb
<h1> 
    Hi 
    <% if @user.first_name %>
        <%= @user.first_name %>!
    <% else %>
        there!
    <% end %>
    
</h1>


<% if user_signed_in? %>
    <p>What would you like to do?</p>
    <ul>
        <li>
            <%= link_to "Change Email or Password", edit_user_registration_path %>
        </li>
        <li>
            <%= link_to "Change Name", edit_user_path(current_user.id) %>
        </li>
        <li>
            <%= link_to "See All Posts", posts_path %>
        </li>
        <li>
            <%= link_to "Add a post", new_post_path %>
        </li>
    </ul>
    
    
<% end %>